<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = '/';

return array(
    'Mclass\\'    => array($vendorDir . '/mclass'),
    'Model\\'     => array ($vendorDir . '/model'),
    'Server\\'    => array ($vendorDir . '/server'),
    'Validate\\'  => array ($vendorDir . '/validate'),
);
